### ISSUE TITLE
Switch monitoring issue using Prometheus. 

### ISSUE THREAD

**Issue by imran-pathan** [prometheus-community/snmp#5]
Hi Team,

- We are getting the issue while monitoring the new Edgecore switch using Prometheus.
Issue: context deadline exceeded , PFA screenshot

- From snmp walk we are getting the switch data but its not monitoring on Prometheus side . Let us know any suggestion for this.

![image](https://user-images.githubusercontent.com/94363445/184110441-b2f412f3-99f1-4e95-a77f-599a9257376f.png)

**Comment by RichiH** [comment]
This looks more like a support request. Please try one of the mechanisms listed at https://prometheus.io/community/

That being said, please verify from the machine you're running snmp_exporter from that you can connect via SNMP, and that the response time does not exceed your configured timeouts.
